import type { Continent } from "./types";

export type Country = { name: string; continent: Continent };

/**
 * Residence list used by the trial rule.
 * Continents follow UN M49. Russia is Europe. Turkey, Cyprus, the Caucasus,
 * and Kazakhstan are Asia. Gulf codes stay Asia so eligibility comes only
 * from the explicit Gulf exception.
 */
export const COUNTRIES: Record<string, Country> = {
  // Africa
  DZ: { name: "Algeria", continent: "Africa" },
  AO: { name: "Angola", continent: "Africa" },
  BJ: { name: "Benin", continent: "Africa" },
  BW: { name: "Botswana", continent: "Africa" },
  BF: { name: "Burkina Faso", continent: "Africa" },
  BI: { name: "Burundi", continent: "Africa" },
  CV: { name: "Cabo Verde", continent: "Africa" },
  CM: { name: "Cameroon", continent: "Africa" },
  CF: { name: "Central African Republic", continent: "Africa" },
  TD: { name: "Chad", continent: "Africa" },
  KM: { name: "Comoros", continent: "Africa" },
  CG: { name: "Congo", continent: "Africa" },
  CD: { name: "Congo (DRC)", continent: "Africa" },
  CI: { name: "Côte d'Ivoire", continent: "Africa" },
  DJ: { name: "Djibouti", continent: "Africa" },
  EG: { name: "Egypt", continent: "Africa" },
  GQ: { name: "Equatorial Guinea", continent: "Africa" },
  ER: { name: "Eritrea", continent: "Africa" },
  SZ: { name: "Eswatini", continent: "Africa" },
  ET: { name: "Ethiopia", continent: "Africa" },
  GA: { name: "Gabon", continent: "Africa" },
  GM: { name: "Gambia", continent: "Africa" },
  GH: { name: "Ghana", continent: "Africa" },
  GN: { name: "Guinea", continent: "Africa" },
  GW: { name: "Guinea-Bissau", continent: "Africa" },
  KE: { name: "Kenya", continent: "Africa" },
  LS: { name: "Lesotho", continent: "Africa" },
  LR: { name: "Liberia", continent: "Africa" },
  LY: { name: "Libya", continent: "Africa" },
  MG: { name: "Madagascar", continent: "Africa" },
  MW: { name: "Malawi", continent: "Africa" },
  ML: { name: "Mali", continent: "Africa" },
  MR: { name: "Mauritania", continent: "Africa" },
  MU: { name: "Mauritius", continent: "Africa" },
  MA: { name: "Morocco", continent: "Africa" },
  MZ: { name: "Mozambique", continent: "Africa" },
  NA: { name: "Namibia", continent: "Africa" },
  NE: { name: "Niger", continent: "Africa" },
  NG: { name: "Nigeria", continent: "Africa" },
  RW: { name: "Rwanda", continent: "Africa" },
  ST: { name: "São Tomé and Príncipe", continent: "Africa" },
  SN: { name: "Senegal", continent: "Africa" },
  SC: { name: "Seychelles", continent: "Africa" },
  SL: { name: "Sierra Leone", continent: "Africa" },
  SO: { name: "Somalia", continent: "Africa" },
  ZA: { name: "South Africa", continent: "Africa" },
  SS: { name: "South Sudan", continent: "Africa" },
  SD: { name: "Sudan", continent: "Africa" },
  TZ: { name: "Tanzania", continent: "Africa" },
  TG: { name: "Togo", continent: "Africa" },
  TN: { name: "Tunisia", continent: "Africa" },
  UG: { name: "Uganda", continent: "Africa" },
  EH: { name: "Western Sahara", continent: "Africa" },
  ZM: { name: "Zambia", continent: "Africa" },
  ZW: { name: "Zimbabwe", continent: "Africa" },

  // Asia, including the six Gulf countries
  AF: { name: "Afghanistan", continent: "Asia" },
  AM: { name: "Armenia", continent: "Asia" },
  AZ: { name: "Azerbaijan", continent: "Asia" },
  BH: { name: "Bahrain", continent: "Asia" },
  BD: { name: "Bangladesh", continent: "Asia" },
  BT: { name: "Bhutan", continent: "Asia" },
  BN: { name: "Brunei", continent: "Asia" },
  KH: { name: "Cambodia", continent: "Asia" },
  CN: { name: "China", continent: "Asia" },
  CY: { name: "Cyprus", continent: "Asia" },
  GE: { name: "Georgia", continent: "Asia" },
  HK: { name: "Hong Kong", continent: "Asia" },
  IN: { name: "India", continent: "Asia" },
  ID: { name: "Indonesia", continent: "Asia" },
  IR: { name: "Iran", continent: "Asia" },
  IQ: { name: "Iraq", continent: "Asia" },
  IL: { name: "Israel", continent: "Asia" },
  JP: { name: "Japan", continent: "Asia" },
  JO: { name: "Jordan", continent: "Asia" },
  KZ: { name: "Kazakhstan", continent: "Asia" },
  KW: { name: "Kuwait", continent: "Asia" },
  KG: { name: "Kyrgyzstan", continent: "Asia" },
  LA: { name: "Laos", continent: "Asia" },
  LB: { name: "Lebanon", continent: "Asia" },
  MO: { name: "Macao", continent: "Asia" },
  MY: { name: "Malaysia", continent: "Asia" },
  MV: { name: "Maldives", continent: "Asia" },
  MN: { name: "Mongolia", continent: "Asia" },
  MM: { name: "Myanmar", continent: "Asia" },
  NP: { name: "Nepal", continent: "Asia" },
  KP: { name: "North Korea", continent: "Asia" },
  OM: { name: "Oman", continent: "Asia" },
  PK: { name: "Pakistan", continent: "Asia" },
  PS: { name: "Palestine", continent: "Asia" },
  PH: { name: "Philippines", continent: "Asia" },
  QA: { name: "Qatar", continent: "Asia" },
  SA: { name: "Saudi Arabia", continent: "Asia" },
  SG: { name: "Singapore", continent: "Asia" },
  KR: { name: "South Korea", continent: "Asia" },
  LK: { name: "Sri Lanka", continent: "Asia" },
  SY: { name: "Syria", continent: "Asia" },
  TW: { name: "Taiwan", continent: "Asia" },
  TJ: { name: "Tajikistan", continent: "Asia" },
  TH: { name: "Thailand", continent: "Asia" },
  TL: { name: "Timor-Leste", continent: "Asia" },
  TR: { name: "Turkey", continent: "Asia" },
  TM: { name: "Turkmenistan", continent: "Asia" },
  AE: { name: "United Arab Emirates", continent: "Asia" },
  UZ: { name: "Uzbekistan", continent: "Asia" },
  VN: { name: "Vietnam", continent: "Asia" },
  YE: { name: "Yemen", continent: "Asia" },

  // Europe
  AL: { name: "Albania", continent: "Europe" },
  AD: { name: "Andorra", continent: "Europe" },
  AT: { name: "Austria", continent: "Europe" },
  BY: { name: "Belarus", continent: "Europe" },
  BE: { name: "Belgium", continent: "Europe" },
  BA: { name: "Bosnia and Herzegovina", continent: "Europe" },
  BG: { name: "Bulgaria", continent: "Europe" },
  HR: { name: "Croatia", continent: "Europe" },
  CZ: { name: "Czechia", continent: "Europe" },
  DK: { name: "Denmark", continent: "Europe" },
  EE: { name: "Estonia", continent: "Europe" },
  FI: { name: "Finland", continent: "Europe" },
  FR: { name: "France", continent: "Europe" },
  DE: { name: "Germany", continent: "Europe" },
  GR: { name: "Greece", continent: "Europe" },
  HU: { name: "Hungary", continent: "Europe" },
  IS: { name: "Iceland", continent: "Europe" },
  IE: { name: "Ireland", continent: "Europe" },
  IT: { name: "Italy", continent: "Europe" },
  XK: { name: "Kosovo", continent: "Europe" },
  LV: { name: "Latvia", continent: "Europe" },
  LI: { name: "Liechtenstein", continent: "Europe" },
  LT: { name: "Lithuania", continent: "Europe" },
  LU: { name: "Luxembourg", continent: "Europe" },
  MT: { name: "Malta", continent: "Europe" },
  MD: { name: "Moldova", continent: "Europe" },
  MC: { name: "Monaco", continent: "Europe" },
  ME: { name: "Montenegro", continent: "Europe" },
  NL: { name: "Netherlands", continent: "Europe" },
  MK: { name: "North Macedonia", continent: "Europe" },
  NO: { name: "Norway", continent: "Europe" },
  PL: { name: "Poland", continent: "Europe" },
  PT: { name: "Portugal", continent: "Europe" },
  RO: { name: "Romania", continent: "Europe" },
  RU: { name: "Russia", continent: "Europe" },
  SM: { name: "San Marino", continent: "Europe" },
  RS: { name: "Serbia", continent: "Europe" },
  SK: { name: "Slovakia", continent: "Europe" },
  SI: { name: "Slovenia", continent: "Europe" },
  ES: { name: "Spain", continent: "Europe" },
  SE: { name: "Sweden", continent: "Europe" },
  CH: { name: "Switzerland", continent: "Europe" },
  UA: { name: "Ukraine", continent: "Europe" },
  GB: { name: "United Kingdom", continent: "Europe" },
  VA: { name: "Vatican City", continent: "Europe" },

  // North America
  AG: { name: "Antigua and Barbuda", continent: "North America" },
  BS: { name: "Bahamas", continent: "North America" },
  BB: { name: "Barbados", continent: "North America" },
  BZ: { name: "Belize", continent: "North America" },
  CA: { name: "Canada", continent: "North America" },
  CR: { name: "Costa Rica", continent: "North America" },
  CU: { name: "Cuba", continent: "North America" },
  DM: { name: "Dominica", continent: "North America" },
  DO: { name: "Dominican Republic", continent: "North America" },
  SV: { name: "El Salvador", continent: "North America" },
  GL: { name: "Greenland", continent: "North America" },
  GD: { name: "Grenada", continent: "North America" },
  GT: { name: "Guatemala", continent: "North America" },
  HT: { name: "Haiti", continent: "North America" },
  HN: { name: "Honduras", continent: "North America" },
  JM: { name: "Jamaica", continent: "North America" },
  MX: { name: "Mexico", continent: "North America" },
  NI: { name: "Nicaragua", continent: "North America" },
  PA: { name: "Panama", continent: "North America" },
  PR: { name: "Puerto Rico", continent: "North America" },
  KN: { name: "Saint Kitts and Nevis", continent: "North America" },
  LC: { name: "Saint Lucia", continent: "North America" },
  VC: { name: "Saint Vincent and the Grenadines", continent: "North America" },
  TT: { name: "Trinidad and Tobago", continent: "North America" },
  US: { name: "United States", continent: "North America" },

  // South America
  AR: { name: "Argentina", continent: "South America" },
  BO: { name: "Bolivia", continent: "South America" },
  BR: { name: "Brazil", continent: "South America" },
  CL: { name: "Chile", continent: "South America" },
  CO: { name: "Colombia", continent: "South America" },
  EC: { name: "Ecuador", continent: "South America" },
  GY: { name: "Guyana", continent: "South America" },
  PY: { name: "Paraguay", continent: "South America" },
  PE: { name: "Peru", continent: "South America" },
  SR: { name: "Suriname", continent: "South America" },
  UY: { name: "Uruguay", continent: "South America" },
  VE: { name: "Venezuela", continent: "South America" },

  // Oceania
  AU: { name: "Australia", continent: "Oceania" },
  FJ: { name: "Fiji", continent: "Oceania" },
  KI: { name: "Kiribati", continent: "Oceania" },
  MH: { name: "Marshall Islands", continent: "Oceania" },
  FM: { name: "Micronesia", continent: "Oceania" },
  NR: { name: "Nauru", continent: "Oceania" },
  NZ: { name: "New Zealand", continent: "Oceania" },
  PW: { name: "Palau", continent: "Oceania" },
  PG: { name: "Papua New Guinea", continent: "Oceania" },
  WS: { name: "Samoa", continent: "Oceania" },
  SB: { name: "Solomon Islands", continent: "Oceania" },
  TO: { name: "Tonga", continent: "Oceania" },
  TV: { name: "Tuvalu", continent: "Oceania" },
  VU: { name: "Vanuatu", continent: "Oceania" },
};

export function countryOptions() {
  return Object.entries(COUNTRIES)
    .map(([code, country]) => ({ code, ...country }))
    .sort((a, b) => a.name.localeCompare(b.name));
}
